//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import Moya
import PromiseKit

// Importing Alamofire became necessary when configuring the NotModifiedPlugin
// but this should not be needed. There is some setting somewhere that must be
// wrong.
import Alamofire


// MARK: - EverclearAuthApi

enum EverclearAuthApi {
    
    case login(loginObject: Encodable)
}

extension EverclearAuthApi {
    
    /// A Dictionary with 'Paths.plist' file content that reflects `EverclearAuthApi` cases
    /// and represents all paths for API
    ///
    static var pathsFile: [String: String] {
        
        if let path = bundle.path(forResource: "AuthPaths", ofType: "plist"),
            let paths = NSDictionary(contentsOfFile: path) as? [String : String] {
            return paths
        }
        return [:]
    }
}


// MARK: - TargetType

extension EverclearAuthApi : TargetType {
    
    var baseURL: URL {
        
        return NetworkApiManager.baseURL
    }
    
    var path: String {
        
        let path = EverclearAuthApi.pathsFile[caseName]!
        return path
    }
    
    var method: Moya.Method {
        
        switch self {
        case .login:
            return .post
        }
    }
    
    var task: Task {
        
        switch self {
              
        case .login(let requestObject):
             
            return .requestCustomJSONEncodable(requestObject, encoder: NetworkApiManager.customEncoder)
        }
    }
}
