//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import Moya
import PromiseKit


// MARK: - EverclearAuthApi

enum NetworkUsersApi {
    
    case user
}

extension NetworkUsersApi {
    
    /// A Dictionary with 'Paths.plist' file content that reflects `EverclearAuthApi` cases
    /// and represents all paths for API
    ///
    static var pathsFile: [String: String] {
        
        if let path = bundle.path(forResource: "UsersPaths", ofType: "plist"),
            let paths = NSDictionary(contentsOfFile: path) as? [String : String] {
            return paths
        }
        return [:]
    }
}


// MARK: - TargetType

extension NetworkUsersApi : TargetType {
    
    var baseURL: URL {
        return NetworkApiManager.apiURL
    }
    
    var path: String {
        
        let path = NetworkUsersApi.pathsFile[caseName]!
        
        switch self {
        default:
            return path
        }
    }
    
    var method: Moya.Method {
        return .get
    }
    
    var task: Task {
        return .requestPlain
    }
}
