//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import PromiseKit
import Moya


/// Extension for NetworkApiManager implements required methods for fetching data from API

// User
//
internal extension NetworkApiManager {
    
    static func getUser(features: Features = [.logging]) -> Promise<User> {
        
        let provider = MoyaProvider<NetworkUsersApi>(with: features)
        let request = NetworkUsersApi.user
        
        return self.requestData(request, with: provider)
    }
}
