//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom MVVM Xcode template.
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController  {

    // Public Properties
    //
    var viewModel: ___VARIABLE_productName:identifier___ViewModelInterface!
    
    
    // Private Properties & Outlets
    //
    
}


//MARK: - Overrides

extension ___VARIABLE_productName:identifier___ViewController {
    
    override func viewDidLoad() {
        
        super.viewDidLoad()
        //
    }
    
    override func viewWillAppear(_ animated: Bool) {
        
        super.viewWillAppear(animated)
        //
    }
    
    override func viewDidAppear(_ animated: Bool) {
        
        super.viewDidAppear(animated)
        //
    }
    
    override func viewDidLayoutSubviews() {
        
        super.viewDidLayoutSubviews()
        
        // Place any view.frame related calculations. In this method view.frame is calculated correctly.
        //
    }
    
    override func viewWillLayoutSubviews() {
        
        super.viewWillLayoutSubviews()
        
        // Place any layout invalidation methods here, like collectionView.collectionViewLayout.invalidateLayout()
        //
    }
}


//MARK: - Private Methods

fileprivate extension ___VARIABLE_productName:identifier___ViewController {
    
}


//MARK: - IBActions

fileprivate extension ___VARIABLE_productName:identifier___ViewController {
    
}


//MARK: - ___VARIABLE_productName:identifier___ViewControllerProtocol

extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewControllerInterface {
    
    func configureWith(_ model: ___VARIABLE_productName:identifier___ViewModelInterface) {
        viewModel = model
    }
}

// Uncomment if view model has a delegate based callblack
//MARK: - ___VARIABLE_productName:identifier___ViewModelDelegate

//extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewModelDelegate {
//
//}
