//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom MVVM Xcode template.
//

import UIKit

class ___VARIABLE_productName:identifier___Router {
    weak var viewController: UIViewController?
}


//MARK: - ___VARIABLE_productName:identifier___RouterProtocol
//
extension ___VARIABLE_productName:identifier___Router: ___VARIABLE_productName:identifier___RouterProtocol {
    
}
