//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom MVVM Xcode template.
//

import UIKit
import Combine

class ___VARIABLE_productName:identifier___ViewModel {
    
    var router: ___VARIABLE_productName:identifier___RouterProtocol?
    weak var moduleOutput: ___VARIABLE_productName:identifier___ModuleOutputProtocol?
    
    // Configure custom init
    //
    init() {
        //TODO: - Initialize binding variables here.
    }
}

//MARK: - ReferralLinkModuleInputProtocol
//
extension ___VARIABLE_productName:identifier___ViewModel: ___VARIABLE_productName:identifier___ModuleInputProtocol {
    
}


//MARK: Private Methods
//
fileprivate extension ___VARIABLE_productName:identifier___ViewModel {
    
}


//MARK: ___VARIABLE_productName:identifier___ViewModelProtocol
//
extension ___VARIABLE_productName:identifier___ViewModel: ___VARIABLE_productName:identifier___ViewModelInterface {
    
    func viewReady() {
        //TODO: - Place any initializations and network calls here.
    }
}
