//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom MVVM Xcode template.
//

import UIKit
import Combine

class ___VARIABLE_productName:identifier___ViewController: UIViewController  {

    // Public Properties
    //
    var viewModel: ___VARIABLE_productName:identifier___ViewModelInterface!
    
    
    // Private Properties & Outlets
    //
    
}


//MARK: - Overrides

extension ___VARIABLE_productName:identifier___ViewController {
    
    override func viewDidLoad() {
        
        super.viewDidLoad()
        bind()
        viewModel.viewReady()
        //
    }
}

extension ___VARIABLE_productName:identifier___ViewControllerInterface {
    
    func bind() {
        //TODO: - Place viewModel's binding here
    }
}


//MARK: - Private Methods

fileprivate extension ___VARIABLE_productName:identifier___ViewController {
    
}


//MARK: - IBActions

fileprivate extension ___VARIABLE_productName:identifier___ViewController {
    
}


//MARK: - ___VARIABLE_productName:identifier___ViewControllerProtocol

extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewControllerInterface {
    
}
