//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom MVVM Xcode template.
//

import UIKit

class ___VARIABLE_productName:identifier___ViewModel {
    
//    Uncomment if view model has a delegate based callblack
//    weak var delegate: ___VARIABLE_productName:identifier___ViewModelDelegate?
    
    // Configure custom init
    //
    init() {
        
    }
}


//MARK: Private Methods
//
fileprivate extension ___VARIABLE_productName:identifier___ViewModel {
    
}


//MARK: ___VARIABLE_productName:identifier___ViewModelProtocol
//
extension ___VARIABLE_productName:identifier___ViewModel: ___VARIABLE_productName:identifier___ViewModelInterface {
    
}
