//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import CoreData


public class ManagedUser: NSManagedObject {

}

extension ManagedUser: CoreDataExportable {
    
    func configure(with object: User, in storage: CoreDataStorageInterface) {
        
        id <<-> Int64(object.id)
    }
    
    func getObject() -> User {
        return User(managedObject: self)
    }
    
    typealias ExportType = User
}


