//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import UIKit
import PromiseKit

final class AppFlowController: UIViewController {
    
    // Static Properties
    //
    static var main: AppFlowController!

    // Public Properties
    //
    var window: UIWindow?
}


// MARK: - Public Methods
//
extension AppFlowController {
    
}


// MARK: - Private Methods
//
private extension AppFlowController {
    
    func launch() {
        
    }
}


//MARK: - ApplicationBehavior
//
extension AppFlowController: ApplicationBehavior {
    
    func application(_ application: UIApplication, willFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        AppFlowController.main = self
        window = UIWindow(frame: UIScreen.main.bounds)
        window?.rootViewController = self
        window?.makeKeyAndVisible()

        launch()
        
        return true
    }
}
