//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import PromiseKit

// Injected:
//
//   For more information about the injection technique being used, and an example of how you can replace
//   what is injected like for tests, see: http://www.danielhall.io/a-swift-y-approach-to-dependency-injection


protocol AccountServiceInjected { }

protocol AccountServiceProtocol {
    
    /// The main login method
    ///
    /// - Parameters:
    ///   - email: Username or email string
    ///   - password: User's password which was created through registration step
    /// - Returns: a Promise object with User model inside.
    ///
    func login(with email: String, password: String) -> Promise<User>
}
