//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import PromiseKit

extension AccountServiceInjected {
    public var accountService: AccountServiceProtocol {  return Services.account }
}

final class AccountService: AccountServiceProtocol, UserServiceInjected {
    
    func login(with email: String, password: String) -> Promise<User> {
        
        firstly {
            NetworkApiManager.login(username: email,
                                      password: password).compactMap { $0.token }
        }.then { token -> Promise<User> in
            //Store token somewhere in keychain if needed
            self.userService.getMyUser()
        }
    }
}
