# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!
workspace '___PROJECTNAME___.xcworkspace'

def basic_pods
    
    # Analytics
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'Firebase'
    
    # Networking / Mappers / Helpers
    pod 'Moya'

    # Utils
    pod 'KeychainAccess'
    pod 'PromiseKit'
    
    # Logging
    pod 'SwiftyBeaver'
end

target '___PROJECTNAME___' do
  basic_pods
end

post_install do |installer|

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end

