//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import SwiftyBeaver

// direct access to the logger across the app
let logger = SwiftyBeaver.self

extension SwiftyBeaver {
    
    static func setupConsole() {
        // add log destinations. at least one is needed!
        
        let console = ConsoleDestination()  // log to Xcode Console
        
        console.levelColor.verbose = "⚪️ "
        console.levelColor.debug = "☑️ "
        console.levelColor.info = "🔵 "
        console.levelColor.warning = "🔶 "
        console.levelColor.error = "❌ "

        // add the destinations to SwiftyBeaver
        logger.addDestination(console)
    }
}
