//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

enum Services {
    
    static var reachability: ReachabilityServiceProtocol = ReachabilityService()
    static var user: UserServiceProtocol = UserService()
    static var account: AccountServiceProtocol = AccountService()
}
