//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation

extension Encodable {
    
    func asDictionary() throws -> [String: Any] {
        
        let data = try NetworkApiManager.customEncoder.encode(self)
        guard let dictionary = try JSONSerialization.jsonObject(with: data, options: .allowFragments) as? [String: Any] else {
            throw NSError()
        }
        return dictionary
    }
}

extension Dictionary {
    
    func merging(_ other: [Key: Value]) -> [Key: Value] {
        return merging(other, uniquingKeysWith: { l,r in r })
    }
}
