//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation

extension NSPredicate {
    
    convenience init(key: String, id: Int64) {
        
        let predicateString = String(format: "%@ == %li", key, id)
        self.init(format: predicateString)
    }
    
    convenience init(id: Int64) {
        
        let predicateString = String(format: "id == %li", id)
        self.init(format: predicateString)
    }
}
