//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation

extension NSPredicate {
    
    enum CompoundType {
        case and
        case or
    }
    
    convenience init(key: String, value: Any) {
        self.init(format: "%@ == %@", key, value as! CVarArg)
    }
    
    convenience init(value: Any) {
        
        self.init(format: "id== %@", value as! CVarArg)
    }
    
    func appending(predicate: NSPredicate, type: CompoundType) -> NSPredicate {
        
        switch type {
        case .and: return NSCompoundPredicate(andPredicateWithSubpredicates: [self, predicate])
        case .or: return NSCompoundPredicate(orPredicateWithSubpredicates: [self, predicate])
        }
    }
}
