//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import UIKit
import CoreData

/// A type responsible for initializing the application's database
public struct AppDatabase {

    public static func openDatabase(in application: UIApplication) {
        
        //Initialize core data stack
        //
        _ = CoreDataStorageController.shared
    }
}
