//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import PromiseKit

// Injected:
//
//   For more information about the injection technique being used, and an example of how you can replace
//   what is injected like for tests, see: http://www.danielhall.io/a-swift-y-approach-to-dependency-injection

protocol UserServiceInjected { }

protocol UserServiceProtocol {

    /// Method for retrieving user
    ///
    /// - Returns: a Promise object with User model inside.
    ///
    func getMyUser() -> Promise<User>
}
