//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import UIKit

// Responding to System Events
public extension AppBehaviorDispatcher {

    // MARK: - Protected Data

    @available(iOS 4.0, *)
    func applicationProtectedDataWillBecomeUnavailable(_ application: UIApplication) {
        
        for behavior in behaviors {
            behavior.applicationProtectedDataWillBecomeUnavailable?(application)
        }
    }

    @available(iOS 4.0, *)
    func applicationProtectedDataDidBecomeAvailable(_ application: UIApplication) {
        
        for behavior in behaviors {
            behavior.applicationProtectedDataDidBecomeAvailable?(application)
        }
    }

    // MARK: - Memory Warning

    @available(iOS 2.0, *)
    func applicationDidReceiveMemoryWarning(_ application: UIApplication) {
        
        for behavior in behaviors {
            behavior.applicationDidReceiveMemoryWarning?(application)
        }
    }

    // MARK: - Time Change

    @available(iOS 2.0, *)
    func applicationSignificantTimeChange(_ application: UIApplication) {
        
        for behavior in behaviors {
            behavior.applicationSignificantTimeChange?(application)
        }
    }
}
