//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import UIKit

// Interacting With HealthKit
public extension AppBehaviorDispatcher {

    @available(iOS 9.0, *)
    func applicationShouldRequestHealthAuthorization(_ application: UIApplication) {
        
        for behavior in behaviors {
            behavior.applicationShouldRequestHealthAuthorization?(application)
        }
    }
}
