//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import UIKit

// Managing Interface Geometry
public extension AppBehaviorDispatcher {

    @available(iOS 2.0, *)
    func application(_ application: UIApplication, willChangeStatusBarOrientation newStatusBarOrientation: UIInterfaceOrientation, duration: TimeInterval) {
        
        for behavior in behaviors {
            behavior.application?(application, willChangeStatusBarOrientation: newStatusBarOrientation, duration: duration)
        }
    }

    @available(iOS 2.0, *)
    func application(_ application: UIApplication, didChangeStatusBarOrientation oldStatusBarOrientation: UIInterfaceOrientation) {
        
        for behavior in behaviors {
            behavior.application?(application, didChangeStatusBarOrientation: oldStatusBarOrientation)
        }
    }

    func application(_ application: UIApplication, willChangeStatusBarFrame newStatusBarFrame: CGRect) {
        
        for behavior in behaviors {
            behavior.application?(application, willChangeStatusBarFrame: newStatusBarFrame)
        }
    }

    func application(_ application: UIApplication, didChangeStatusBarFrame oldStatusBarFrame: CGRect) {
        
        for behavior in behaviors {
            behavior.application?(application, didChangeStatusBarFrame: oldStatusBarFrame)
        }
    }
}
