//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Foundation
import CoreData

extension User: CoreDataCompatible {
    
    var primaryKey: Int64 {
        return id
    }
    
    init(managedObject: ManagedUser) {
        
        id = managedObject.id
    }
    
    typealias ManagedType = ManagedUser
}
