//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is generated by custom SKELETON Xcode template.
//

import Moya
import Alamofire
import KeychainAccess

extension MoyaProvider {
    
    /// Simplified init method for MoyaProvider with ability to add feature flags
    /// - Parameters:
    ///   - features: Features structure with set of available features for current provider
    ///
    convenience init(with features: NetworkApiManager.Features = []) {
        
        var plugins: [PluginType] = []
        if features.contains(.logging) {
            plugins.append(loggerPlugin)
        }
        
        // Using a stubClosure for the .erroring feature also because
        // otherwise the endpointClosure's sampleResponseClosure won't
        // get called by Moya.
        let stubClosure: MoyaProvider<Target>.StubClosure = features.contains(.stubbing) ? MoyaProvider.immediatelyStub : MoyaProvider.neverStub
        
        let endpointClosure: MoyaProvider<Target>.EndpointClosure = MoyaProvider.defaultEndpointMapping
        
        // Setup NotModifiedPlugin (see plugin file's comments for more info)
        let session: Session = Session.default
        
        if let urlCache = session.session.configuration.urlCache {
            plugins.append(NotModifiedPlugin(urlCache: urlCache))
        }
        self.init(endpointClosure: endpointClosure, stubClosure: stubClosure, session: session, plugins: plugins)
    }
}
